language: swift
osx_image: xcode9.4

cache:
  - cocoapods
  - bundler

before_install:
  - gem update cocoapods
  - pod install --repo-update
  - brew update
  - brew install swiftlint || true

before_script:
  - bundle exec danger

script:
  - set -o pipefail
  - xcodebuild clean test -workspace rothKeystore.xcworkspace -scheme "rothKeystore" -destination 'platform=iOS Simulator,name=iPhone 8' -quiet
  - xcodebuild clean test -workspace rothKeystore.xcworkspace -scheme "rothKeystore" -destination 'platform=iOS Simulator,name=iPhone 5' -quiet

after_success:
  - bash <(curl -s https://codecov.io/bash)
